Fix splitting of training data and evaluation

diff --git a/bin/eval b/bin/eval
--- a/bin/eval
+++ b/bin/eval
@@ -11,15 +11,15 @@ if ! [[ -d "${MODEL_DIR}" ]]; then
 fi
 
 TEST_LYT_DIR="${MODEL_DIR}/TEST_LYT"
+TEST_REFS_DIR="${MODEL_DIR}/TEST_REFS"
 TEST_SEG_DIR="${MODEL_DIR}/TEST_SEG"
-EXPARSER_LYT_INPUT_DIR=./Data/2-layouts
-EXPARSER_SEG_INPUT_DIR=./Data/3-refs
-EXPARSER_SEG_OUTPUT_DIR=./Data/3-refs_seg
-DEF_SEG_DIR="./EXparser/Dataset/default/SEG"
+EXPARSER_LAYOUT_DIR=./Data/2-layouts
+EXPARSER_REFS_DIR=./Data/3-refs
+EXPARSER_SEG_DIR=./Data/3-refs_seg
 
 
-if ! [[ -d "$TEST_LYT_DIR" ]] || ! [[ -d "${TEST_SEG_DIR}" ]] ; then
-  echo "Model $MODEL_NAME is missing the TEST_LYT and/or TEST_SEG folders"
+if ! [[ -d "$TEST_LYT_DIR" ]] || ! [[ -d "${TEST_REFS_DIR}" ]] || ! [[ -d "${TEST_SEG_DIR}" ]]; then
+  echo "Model $MODEL_NAME is missing the TEST_LYT and/or TEST_REFS and/or TEST_SEG folders"
   exit 1
 fi
 
@@ -31,18 +31,10 @@ echo
 
 # clean subfolders and copy layout evaluation data
 find ./Data/ -type f -not -name '.*' -exec rm {} +
-cp $TEST_LYT_DIR/* $EXPARSER_LYT_INPUT_DIR
+cp $TEST_LYT_DIR/* $EXPARSER_LAYOUT_DIR
 
 # run exparser to produce extracted references
 docker run -it --rm -v $(pwd):/app excite_toolchain exparser $MODEL_NAME
-
-echo
-echo "=========================================================================================="
-echo "Running segmentation on correctly extracted lines, please wait..."
-echo "=========================================================================================="
-echo
-
-docker run -it --rm -v $(pwd):/app excite_toolchain segmentation $MODEL_NAME $TEST_SEG_DIR
 
 echo
 echo "=========================================================================================="
@@ -51,7 +43,15 @@ echo "==========================================================================
 echo
 
 #  gold: SEG files without tags, input: exparser extraction output
-docker run -it --rm -v $(pwd):/app excite_toolchain eval $TEST_SEG_DIR $EXPARSER_SEG_INPUT_DIR extr $MODEL_DIR
+docker run -it --rm -v $(pwd):/app excite_toolchain eval $TEST_REFS_DIR $EXPARSER_REFS_DIR extr $MODEL_DIR
+
+echo
+echo "=========================================================================================="
+echo "Running segmentation on correctly extracted lines, please wait..."
+echo "=========================================================================================="
+echo
+
+docker run -it --rm -v $(pwd):/app excite_toolchain segmentation $MODEL_NAME $TEST_REFS_DIR
 
 echo
 echo "=========================================================================================="
@@ -60,6 +60,6 @@ echo "==========================================================================
 echo
 
 # gold: original SEG files, input: output of exparser segmentation
-docker run -it --rm -v $(pwd):/app excite_toolchain eval $DEF_SEG_DIR $EXPARSER_SEG_OUTPUT_DIR seg $MODEL_DIR
+docker run -it --rm -v $(pwd):/app excite_toolchain eval $TEST_SEG_DIR $EXPARSER_SEG_DIR seg $MODEL_DIR
 
 echo "Logfiles and CSV data have been written to ./Exparser/Dataset/${MODEL_NAME}"
